voxel_size: [0.075, 0.075, 0.2]
point_cloud_range: [-54.0, -54.0, -5.0, 54.0, 54.0, 3.0]

model:
  encoders:
    camera:
      backbone:
        type: SwiftFormer_L1
        mlp_ratio: 4
        drop_rate: 0.
        drop_path_rate: 0.2
        num_classes: 1000
        down_patch_size: 3
        down_stride: 2
        down_pad: 1
        use_layer_scale: True
        fork_feat: True
        pretrained: True
        init_cfg:
          type: Pretrained
          checkpoint: http://rean-song-bucket.oss-cn-guangzhou.aliyuncs.com/autoDL/BEVFusion/ckpts/SwiftFormer_L1.pth
        vit_num: 1
        distillation: False
      neck:
        in_channels: [48, 96, 192, 384]
      vtransform:
        xbound: [-54.0, 54.0, 0.3]
        ybound: [-54.0, 54.0, 0.3]
        height_expand: True
        add_depth_features: True
        is_xtransform: false
    lidar:
      voxelize:
        point_cloud_range: ${point_cloud_range}
        voxel_size: ${voxel_size}
        max_voxels: [120000, 160000]
      backbone:
        sparse_shape: [1440, 1440, 41]

  heads:
    object:
      train_cfg:
        grid_size: [1440, 1440, 41]
      test_cfg:
        grid_size: [1440, 1440, 41]

lr_config:
  policy: CosineAnnealing
  warmup: linear
  warmup_iters: 500
  warmup_ratio: 0.33333333
  min_lr_ratio: 1.0e-3

log_config:
  interval: 50
  hooks:
    -
      type: TextLoggerHook
    -
      type: TensorboardLoggerHook
    -
      type: WandbLoggerHook
      init_kwargs: {'project': 'BEVFusion-Lite', 'name': 'fin_swift'}
